const exclusions = [
  "Jurassic Park",
  "The Lost World: Jurassic Park",
  "Jurassic World",
  "Jurassic World: Fallen Kingdom",
  "Monty Python and the Holy Grail",
  "And Now for Something Completely Different",
  "Monty Python's Life of Brian",
  "Monty Python Live at the Hollywood Bowl",
  "Monty Python's The Meaning of Life",
  "The Crimson Permanent Assurance",
  "A Liar's Autobiography: The Untrue Story of Monty Python's Graham Chapman",
  "The Princess Bride",
  "Monty Python Live (Mostly)",
  "Child's Play",
  "Absolutely Anything",
  "The Wind in the Willows",
  "The Zero Imperative",
  "The Evil Dead",
  "Star Trek: The Motion Picture",
  "Star Trek II: The Wrath of Khan",
  "Star Trek III: The Search for Spock",
  "Star Trek IV: The Voyage Home",
  "Star Trek V: The Final Frontier",
  "Star Trek VI: The Undiscovered Country",
  "Star Trek",
  "Star Trek Into Darkness",
  "For the Love of Spock",
];

export default exclusions;
